version: '3.4'

services:
  tha.chooseyouradventure.webapi:
    image: ${DOCKER_REGISTRY-}thachooseyouradventurewebapi
    build:
      context: .
      dockerfile: Tha.ChooseYourAdventure.WebAPI/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
        SA_PASSWORD: "Abcd@1234"
        ACCEPT_EULA: "Y"